# GUI Installer Configuration
ui:
  theme: "corporate-blue"
  title: "Go Installer GUI Example"

branding:
  primary_color: "#1e3a8a"
  secondary_color: "#3b82f6"
  company_name: "Go Installer Team"

screens:
  welcome:
    enabled: true
    title: "Welcome to Go Installer"
    message: "This GUI installer demonstrates the Setup-Kit framework with theming support."
    position: 1

  license:
    enabled: true
    title: "License Agreement"
    message: "Please read and accept the MIT license to continue."
    position: 2

  components:
    enabled: true
    title: "Select Components"
    message: "Choose which components to install."
    position: 3

  directory:
    enabled: true
    title: "Installation Directory"
    message: "Choose where to install the application."
    position: 4

  installation:
    enabled: true
    title: "Installing Components"
    message: "Please wait while the selected components are being installed..."
    position: 5

  finish:
    enabled: true
    title: "Installation Complete"
    message: "Go Installer GUI Example has been successfully installed!"
    position: 6
    properties:
      show_launch_option: true
