# Corporate installer configuration
# Professional theme with corporate branding

ui:
  theme: "corporate-blue"
  title: "Enterprise Software Installer"
  auto_theme: false

branding:
  primary_color: "#1e3a8a"
  secondary_color: "#3b82f6"
  logo: "assets/corporate-logo.png"
  font_family: "'Segoe UI', sans-serif"
  company_name: "Enterprise Corp"

screens:
  welcome:
    enabled: true
    title: "Welcome to Enterprise Software"
    message: "This installer will install Enterprise Software on your system. Please ensure you have administrator privileges."
    position: 1

  license:
    enabled: true
    title: "Software License Agreement"
    message: "Please carefully read the license agreement. You must accept the terms to proceed."
    position: 2

  components:
    enabled: true
    title: "Feature Selection"
    message: "Select the features you want to install. Core features are required."
    position: 3

  directory:
    enabled: true
    title: "Installation Location"
    message: "Select the installation directory. Default location is recommended for enterprise deployments."
    position: 4
    properties:
      default_path: "C:\\Program Files\\Enterprise\\Software"

  installation:
    enabled: true
    title: "Installing Features"
    message: "Installing selected features. This may take several minutes..."
    position: 5

  finish:
    enabled: true
    title: "Installation Successful"
    message: "Enterprise Software has been successfully installed and is ready to use."
    position: 6
    properties:
      show_launch_option: false
      show_readme_option: true
